version: "3.8"

services:
  member-info-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: member-info-app
    restart: always
    networks:
      - app-network
    image: notcis07/memberinfo:1.0.1

networks:
  app-network:
    external: true
